# Generated by Django 4.2.23 on 2025-08-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='user_name',
        ),
    ]
