# Generated by Django 4.2.23 on 2025-08-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile',
            field=models.FileField(default=None, upload_to=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
