# Generated by Django 4.2.23 on 2025-08-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_person_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='profile',
        ),
    ]
