# Generated by Django 4.2.23 on 2025-08-29 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_remove_person_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile',
            field=models.FileField(default=django.utils.timezone.now, upload_to=None),
            preserve_default=False,
        ),
    ]
