# Generated by Django 4.2.23 on 2025-08-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_person_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
