# Generated by Django 4.2.23 on 2025-08-29 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_alter_person_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='prof',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
